// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/evm/abi/encode": {
            "post": {
                "description": "Returns the ABI-encoded calldata (4-byte selector + packed arguments) for the given signature and args.\nSignature must be in canonical form — no spaces, no parameter names (e.g. \"transfer(address,uint256)\").\nSupported types: address | bool | string | bytes | bytes1–bytes32 | uint8/16/32/64/128/256 | int8/16/32/64/128/256\nTuple, array, and slice types are not yet supported.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "abi"
                ],
                "summary": "ABI-encode a function call",
                "parameters": [
                    {
                        "description": "Function signature and arguments",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/misc.EncodeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/misc.EncodeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/evm/abi/selector": {
            "post": {
                "description": "Returns the 4-byte selector for the given function signature",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "abi"
                ],
                "summary": "Compute ABI function selector",
                "parameters": [
                    {
                        "description": "Function signature",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/misc.SelectorRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/misc.SelectorResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/evm/rpc/balance": {
            "post": {
                "description": "Returns the balance for the given address at the specified block in decimal and hex",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rpc"
                ],
                "summary": "Get balance for address",
                "parameters": [
                    {
                        "description": "Address and block",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/misc.BalanceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/misc.BalanceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/evm/rpc/block-number": {
            "post": {
                "description": "Returns the latest block number in decimal and hex",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rpc"
                ],
                "summary": "Get block number",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/misc.BlockNumberResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/evm/rpc/call": {
            "post": {
                "description": "Executes eth_call and returns the raw result",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rpc"
                ],
                "summary": "Execute a read-only contract call",
                "parameters": [
                    {
                        "description": "Call parameters",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/misc.CallRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/evm/rpc/chain-id": {
            "post": {
                "description": "Returns the chain ID of the connected network as a decimal integer",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rpc"
                ],
                "summary": "Get chain ID",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/misc.ChainIDResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/evm/rpc/code": {
            "post": {
                "description": "Returns the deployed code for the given address and whether it is a contract",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rpc"
                ],
                "summary": "Get code for address",
                "parameters": [
                    {
                        "description": "Address and block",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/misc.CodeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/misc.CodeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/evm/rpc/fee/base": {
            "post": {
                "description": "Returns the latest block baseFeePerGas in decimal and hex",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rpc"
                ],
                "summary": "Get base fee per gas",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/misc.BaseFeePerGasResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/evm/rpc/fee/max": {
            "post": {
                "description": "Returns max_fee_per_gas calculated as base_fee_per_gas * 2 + max_priority_fee_per_gas",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rpc"
                ],
                "summary": "Get max fee per gas",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/misc.MaxFeePerGasResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/evm/rpc/fee/priority": {
            "post": {
                "description": "Returns the recommended priority fee per gas in decimal and hex",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rpc"
                ],
                "summary": "Get max priority fee per gas",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/misc.MaxPriorityFeePerGasResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/evm/rpc/gas/estimate": {
            "post": {
                "description": "Returns the estimated gas limit for the given transaction parameters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rpc"
                ],
                "summary": "Estimate gas for a transaction",
                "parameters": [
                    {
                        "description": "Transaction parameters",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/misc.EstimateGasRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/misc.EstimateGasResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/evm/rpc/gas/price": {
            "post": {
                "description": "Returns the current gas price in decimal and hex",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rpc"
                ],
                "summary": "Get gas price",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/misc.GasPriceResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/evm/rpc/nonce": {
            "post": {
                "description": "Returns the pending transaction count (nonce) for the given address as a decimal integer",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rpc"
                ],
                "summary": "Get nonce for address",
                "parameters": [
                    {
                        "description": "Address",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/misc.NonceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/misc.NonceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/evm/rpc/transaction": {
            "post": {
                "description": "Returns transaction details for the given tx hash",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rpc"
                ],
                "summary": "Get transaction by hash",
                "parameters": [
                    {
                        "description": "Transaction hash",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/misc.TransactionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/evm/rpc/transaction/receipt": {
            "post": {
                "description": "Returns the transaction receipt for the given tx hash",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rpc"
                ],
                "summary": "Get transaction receipt by hash",
                "parameters": [
                    {
                        "description": "Transaction hash",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/misc.TransactionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/evm/rpc/transaction/send": {
            "post": {
                "description": "Broadcasts a signed raw transaction with eth_sendRawTransaction",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rpc"
                ],
                "summary": "Send signed raw transaction",
                "parameters": [
                    {
                        "description": "Signed raw transaction",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/misc.SendTransactionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/misc.SendTransactionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/evm/tool/address/checksum/eip55": {
            "post": {
                "description": "Returns the EIP-55 mixed-case checksum encoding for the given address",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tool"
                ],
                "summary": "Convert address to EIP-55 checksum format",
                "parameters": [
                    {
                        "description": "Address",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/misc.ChecksumEIP55Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/misc.ChecksumEIP55Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/evm/tool/crypto/derive": {
            "post": {
                "description": "Returns the public key and address derived from the given private key",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tool"
                ],
                "summary": "Derive key set from private key",
                "parameters": [
                    {
                        "description": "Private key",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/misc.DeriveKeyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/misc.DeriveKeyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/evm/tool/unit/convert/decimal": {
            "post": {
                "description": "Converts a decimal amount from one Ethereum unit to another",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tool"
                ],
                "summary": "Convert amount between wei, gwei, and ether",
                "parameters": [
                    {
                        "description": "Unit conversion",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/misc.UnitConvertDecimalRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/misc.UnitConvertDecimalResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/evm/v1/hash/keccak256/legacy": {
            "post": {
                "description": "Computes the Keccak256 hash of the given message with no prefix applied (no EIP standard)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hash"
                ],
                "summary": "Compute raw Keccak256 hash",
                "parameters": [
                    {
                        "description": "Message to hash",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.Keccak256LegacyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.Keccak256LegacyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/evm/v1/hash/keccak256/personal": {
            "post": {
                "description": "Prepends the EIP-191 personal sign prefix (\"\\x19Ethereum Signed Message:\\n\" + length) to the message and returns the Keccak256 hash — matches the digest produced by eth_sign / personal_sign",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hash"
                ],
                "summary": "Compute Keccak256 hash with EIP-191 prefix",
                "parameters": [
                    {
                        "description": "Message to hash",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.Keccak256PersonalRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.Keccak256PersonalResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/evm/v1/sign": {
            "post": {
                "description": "Signs a hex-encoded 32-byte digest with the given private key using raw secp256k1 ECDSA. Hashing is the caller's responsibility — use the hash endpoints to produce the digest before calling this.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sign"
                ],
                "summary": "Sign a pre-computed hash",
                "parameters": [
                    {
                        "description": "Address and digest",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.SignRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.SignResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/evm/v1/sign/verify/by-address": {
            "post": {
                "description": "Recovers the signer's address from the signature via ecrecover and compares it against the provided address",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sign"
                ],
                "summary": "Verify a signature against an address",
                "parameters": [
                    {
                        "description": "Hash, address, and signature",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.VerifyByAddressRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.VerifyByAddressResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/evm/v1/sign/verify/by-public-key": {
            "post": {
                "description": "Recovers the signer's public key from the signature via ecrecover and compares it against the provided public key",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sign"
                ],
                "summary": "Verify a signature against a public key",
                "parameters": [
                    {
                        "description": "Hash, public key, and signature",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.VerifyByPublicKeyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.VerifyByPublicKeyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/evm/v1/transaction/dynamic-fee/build": {
            "post": {
                "description": "Constructs an unsigned EIP-1559 transaction for native ETH transfer and returns the encoded signing payload and signing hash",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transaction"
                ],
                "summary": "Build an unsigned dynamic fee native transfer transaction",
                "parameters": [
                    {
                        "description": "Transaction fields",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.BuildDynamicFeeTransactionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.BuildDynamicFeeTransactionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/evm/v1/transaction/dynamic-fee/sign": {
            "post": {
                "description": "Decodes an unsigned EIP-1559 payload, signs it with the key for the given address, and returns the signed raw transaction and tx hash",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transaction"
                ],
                "summary": "Sign an unsigned dynamic fee native transfer transaction",
                "parameters": [
                    {
                        "description": "Address and unsigned RLP",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.SignDynamicFeeTransactionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.SignDynamicFeeTransactionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/evm/v1/transaction/legacy/build": {
            "post": {
                "description": "Constructs an unsigned EIP-155 legacy transaction for native ETH transfer and returns the RLP encoding and signing hash",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transaction"
                ],
                "summary": "Build an unsigned legacy native transfer transaction",
                "parameters": [
                    {
                        "description": "Transaction fields",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.BuildLegacyTransactionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.BuildLegacyTransactionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/evm/v1/transaction/legacy/sign": {
            "post": {
                "description": "Decodes an unsigned legacy RLP, signs it with the key for the given address, and returns the signed raw transaction and tx hash",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transaction"
                ],
                "summary": "Sign an unsigned legacy native transfer transaction",
                "parameters": [
                    {
                        "description": "Address and unsigned RLP",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.SignLegacyTransactionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.SignLegacyTransactionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/evm/v2/transfers/native/eip1559": {
            "post": {
                "description": "Signs and broadcasts a dynamic-fee ETH transfer transaction",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transfer"
                ],
                "summary": "Send ETH (EIP-1559)",
                "parameters": [
                    {
                        "description": "Transfer request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v2.transferRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v2.transferResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "504": {
                        "description": "Gateway Timeout",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "misc.BalanceRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "0xEbD69375..."
                },
                "block": {
                    "type": "string",
                    "example": "latest"
                }
            }
        },
        "misc.BalanceResponse": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "string"
                },
                "balance_hex": {
                    "type": "string"
                },
                "ether": {
                    "type": "string"
                },
                "gwei": {
                    "type": "string"
                },
                "wei": {
                    "type": "string"
                }
            }
        },
        "misc.BaseFeePerGasResponse": {
            "type": "object",
            "properties": {
                "base_fee_per_gas": {
                    "type": "string"
                },
                "base_fee_per_gas_hex": {
                    "type": "string"
                },
                "ether": {
                    "type": "string"
                },
                "gwei": {
                    "type": "string"
                },
                "wei": {
                    "type": "string"
                }
            }
        },
        "misc.BlockNumberResponse": {
            "type": "object",
            "properties": {
                "block_number": {
                    "type": "integer"
                },
                "block_number_hex": {
                    "type": "string"
                }
            }
        },
        "misc.CallRequest": {
            "type": "object",
            "properties": {
                "block": {
                    "type": "string",
                    "example": "latest"
                },
                "data": {
                    "type": "string",
                    "example": "0x70a08231..."
                },
                "from": {
                    "type": "string",
                    "example": "0xEbD69375..."
                },
                "to": {
                    "type": "string",
                    "example": "0x8336c196..."
                }
            }
        },
        "misc.ChainIDResponse": {
            "type": "object",
            "properties": {
                "chain_id": {
                    "type": "integer"
                },
                "chain_id_hex": {
                    "type": "string"
                }
            }
        },
        "misc.ChecksumEIP55Request": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "0xEbD69375..."
                }
            }
        },
        "misc.ChecksumEIP55Response": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                }
            }
        },
        "misc.CodeRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "0xEbD69375..."
                },
                "block": {
                    "type": "string",
                    "example": "latest"
                }
            }
        },
        "misc.CodeResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "is_contract": {
                    "type": "boolean"
                }
            }
        },
        "misc.DeriveKeyRequest": {
            "type": "object",
            "properties": {
                "private_key": {
                    "type": "string",
                    "example": "0xea66255f..."
                }
            }
        },
        "misc.DeriveKeyResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "private_key": {
                    "type": "string"
                },
                "public_key": {
                    "type": "string"
                }
            }
        },
        "misc.EncodeRequest": {
            "type": "object",
            "properties": {
                "args": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "[\"0xDa70aA79...\"",
                        "\"1000000000000000000\"]"
                    ]
                },
                "signature": {
                    "type": "string",
                    "example": "transfer(address,uint256)"
                }
            }
        },
        "misc.EncodeResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                }
            }
        },
        "misc.EstimateGasRequest": {
            "type": "object",
            "properties": {
                "block": {
                    "type": "string",
                    "example": "latest"
                },
                "data": {
                    "type": "string",
                    "example": "0x"
                },
                "from": {
                    "type": "string",
                    "example": "0xEbD69375..."
                },
                "to": {
                    "type": "string",
                    "example": "0x8336c196..."
                },
                "value": {
                    "type": "string",
                    "example": "1000000000000000000"
                }
            }
        },
        "misc.EstimateGasResponse": {
            "type": "object",
            "properties": {
                "ether": {
                    "type": "string"
                },
                "gas_limit": {
                    "type": "integer"
                },
                "gas_limit_hex": {
                    "type": "string"
                },
                "gwei": {
                    "type": "string"
                },
                "wei": {
                    "type": "string"
                }
            }
        },
        "misc.GasPriceResponse": {
            "type": "object",
            "properties": {
                "ether": {
                    "type": "string"
                },
                "gas_price": {
                    "type": "string"
                },
                "gas_price_hex": {
                    "type": "string"
                },
                "gwei": {
                    "type": "string"
                },
                "wei": {
                    "type": "string"
                }
            }
        },
        "misc.MaxFeePerGasResponse": {
            "type": "object",
            "properties": {
                "ether": {
                    "type": "string"
                },
                "gwei": {
                    "type": "string"
                },
                "max_fee_per_gas": {
                    "type": "string"
                },
                "max_fee_per_gas_hex": {
                    "type": "string"
                },
                "wei": {
                    "type": "string"
                }
            }
        },
        "misc.MaxPriorityFeePerGasResponse": {
            "type": "object",
            "properties": {
                "ether": {
                    "type": "string"
                },
                "gwei": {
                    "type": "string"
                },
                "max_priority_fee_per_gas": {
                    "type": "string"
                },
                "max_priority_fee_per_gas_hex": {
                    "type": "string"
                },
                "wei": {
                    "type": "string"
                }
            }
        },
        "misc.NonceRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "0xEbD69375..."
                },
                "block": {
                    "type": "string",
                    "example": "pending"
                }
            }
        },
        "misc.NonceResponse": {
            "type": "object",
            "properties": {
                "nonce": {
                    "type": "integer"
                },
                "nonce_hex": {
                    "type": "string"
                }
            }
        },
        "misc.SelectorRequest": {
            "type": "object",
            "properties": {
                "signature": {
                    "type": "string",
                    "example": "transfer(address,uint256)"
                }
            }
        },
        "misc.SelectorResponse": {
            "type": "object",
            "properties": {
                "selector": {
                    "type": "string"
                }
            }
        },
        "misc.SendTransactionRequest": {
            "type": "object",
            "properties": {
                "raw_tx": {
                    "type": "string",
                    "example": "0x02f8..."
                }
            }
        },
        "misc.SendTransactionResponse": {
            "type": "object",
            "properties": {
                "tx_hash": {
                    "type": "string"
                }
            }
        },
        "misc.TransactionRequest": {
            "type": "object",
            "properties": {
                "tx_hash": {
                    "type": "string",
                    "example": "0xabc123..."
                }
            }
        },
        "misc.UnitConvertDecimalRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string",
                    "example": "1"
                },
                "from": {
                    "type": "string",
                    "example": "ether"
                },
                "to": {
                    "type": "string",
                    "example": "wei"
                }
            }
        },
        "misc.UnitConvertDecimalResponse": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "unit": {
                    "type": "string"
                }
            }
        },
        "v1.BuildDynamicFeeTransactionRequest": {
            "type": "object",
            "properties": {
                "chain_id": {
                    "type": "string",
                    "example": "20001209"
                },
                "data": {
                    "type": "string",
                    "example": "0x"
                },
                "gas_limit": {
                    "type": "integer",
                    "example": 21000
                },
                "max_fee_per_gas": {
                    "type": "string",
                    "example": "3000000000"
                },
                "max_priority_fee_per_gas": {
                    "type": "string",
                    "example": "1500000000"
                },
                "nonce": {
                    "type": "integer",
                    "example": 0
                },
                "to": {
                    "type": "string",
                    "example": "0x8336c196ABb9E7092C879C28D352b39d3f2f3D7A"
                },
                "value": {
                    "type": "string",
                    "example": "1000000000000000000"
                }
            }
        },
        "v1.BuildDynamicFeeTransactionResponse": {
            "type": "object",
            "properties": {
                "signing_hash": {
                    "type": "string"
                },
                "unsigned_rlp": {
                    "type": "string"
                }
            }
        },
        "v1.BuildLegacyTransactionRequest": {
            "type": "object",
            "properties": {
                "chain_id": {
                    "type": "string",
                    "example": "20001209"
                },
                "data": {
                    "type": "string",
                    "example": "0x"
                },
                "gas_limit": {
                    "type": "integer",
                    "example": 21000
                },
                "gas_price": {
                    "type": "string",
                    "example": "20000000000"
                },
                "nonce": {
                    "type": "integer",
                    "example": 0
                },
                "to": {
                    "type": "string",
                    "example": "0x8336c196ABb9E7092C879C28D352b39d3f2f3D7A"
                },
                "value": {
                    "type": "string",
                    "example": "1000000000000000000"
                }
            }
        },
        "v1.BuildLegacyTransactionResponse": {
            "type": "object",
            "properties": {
                "signing_hash": {
                    "type": "string"
                },
                "unsigned_rlp": {
                    "type": "string"
                }
            }
        },
        "v1.Keccak256LegacyRequest": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "hello world!"
                }
            }
        },
        "v1.Keccak256LegacyResponse": {
            "type": "object",
            "properties": {
                "digest": {
                    "type": "string"
                }
            }
        },
        "v1.Keccak256PersonalRequest": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "hello world!"
                }
            }
        },
        "v1.Keccak256PersonalResponse": {
            "type": "object",
            "properties": {
                "digest": {
                    "type": "string"
                }
            }
        },
        "v1.SignDynamicFeeTransactionRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "0xEbD69375..."
                },
                "unsigned_rlp": {
                    "type": "string",
                    "example": "0x02f8..."
                }
            }
        },
        "v1.SignDynamicFeeTransactionResponse": {
            "type": "object",
            "properties": {
                "raw_transaction": {
                    "type": "string"
                },
                "tx_hash": {
                    "type": "string"
                }
            }
        },
        "v1.SignLegacyTransactionRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "0xEbD69375..."
                },
                "unsigned_rlp": {
                    "type": "string",
                    "example": "0xec8085..."
                }
            }
        },
        "v1.SignLegacyTransactionResponse": {
            "type": "object",
            "properties": {
                "raw_transaction": {
                    "type": "string"
                },
                "tx_hash": {
                    "type": "string"
                }
            }
        },
        "v1.SignRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "0xEbD69375..."
                },
                "digest": {
                    "type": "string",
                    "example": "0xa1b2c3d4..."
                }
            }
        },
        "v1.SignResponse": {
            "type": "object",
            "properties": {
                "signature": {
                    "type": "string"
                }
            }
        },
        "v1.VerifyByAddressRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "0xAbCd1234..."
                },
                "hash": {
                    "type": "string",
                    "example": "0xa1b2c3d4..."
                },
                "signature": {
                    "type": "string",
                    "example": "0xa1b2c3d4..."
                }
            }
        },
        "v1.VerifyByAddressResponse": {
            "type": "object",
            "properties": {
                "result": {
                    "type": "boolean"
                }
            }
        },
        "v1.VerifyByPublicKeyRequest": {
            "type": "object",
            "properties": {
                "hash": {
                    "type": "string",
                    "example": "0xa1b2c3d4..."
                },
                "public_key": {
                    "type": "string",
                    "example": "0x04a1b2c3..."
                },
                "signature": {
                    "type": "string",
                    "example": "0xa1b2c3d4..."
                }
            }
        },
        "v1.VerifyByPublicKeyResponse": {
            "type": "object",
            "properties": {
                "result": {
                    "type": "boolean"
                }
            }
        },
        "v2.transferRequest": {
            "type": "object",
            "properties": {
                "from": {
                    "description": "sender address",
                    "type": "string"
                },
                "to": {
                    "type": "string"
                },
                "value": {
                    "description": "wei as decimal string",
                    "type": "string"
                }
            }
        },
        "v2.transferResponse": {
            "type": "object",
            "properties": {
                "tx_hash": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:33152",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "evmlab API",
	Description:      "Ethereum transaction API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
